param(
  [Parameter(Mandatory = $true, Position = 0)]
  [ValidateSet('ziro', 'hornbill')]
  [string]$Festival
)

$activeFile = Join-Path $PSScriptRoot 'active.ts'
$exportLine = "export { ${Festival}Festival as activeFestival } from './${Festival}'"

Set-Content -Path $activeFile -Value @(
  '// Generated by switch-festival.ps1. Change the active festival with the documented command.'
  $exportLine
) -Encoding utf8

Write-Output "Active festival set to $Festival."
